# Status banner on local TTY (/etc/issue) and SSH login (/etc/motd).
#
# Refreshes every minute via a systemd timer so DHCP changes show up
# without re-login. Agetty re-reads /etc/issue on every login render, so
# we can just rewrite the file and the next prompt picks it up.
#
# Content: hostname, per-interface IP+MAC, and dany's SSH pubkey (so
# you can register it on GitHub from a freshly-imaged VM without an SSH
# session). The pubkey is generated by ./default.nix's
# devhost-user-ssh-key oneshot; this banner reads what's on disk.
{ pkgs, lib, ... }:

let
  writeBanner = pkgs.writeShellScript "devhost-write-banner" ''
    set -eu
    PATH=${
      lib.makeBinPath (
        with pkgs;
        [
          iproute2
          coreutils
          gawk
        ]
      )
    }

    pubkey_file=/home/dany/.ssh/id_ed25519.pub
    pubkey=$( [ -r "$pubkey_file" ] && cat "$pubkey_file" || echo "(not yet generated)" )

    # interfaces: name, primary IPv4, MAC. Skip loopback and down ifaces.
    ifaces=$(
      ip -o -4 addr show scope global up \
        | awk '{ split($4, a, "/"); printf "  %-8s %s", $2, a[1];
                 cmd = "cat /sys/class/net/" $2 "/address";
                 cmd | getline mac; close(cmd);
                 printf "  %s\n", mac }'
    )
    [ -n "$ifaces" ] || ifaces="  (no interfaces up)"

    {
      echo ""
      echo "=== devhost ==="
      echo "hostname: $(hostname)"
      echo "interfaces:"
      echo "$ifaces"
      echo ""
      echo "ssh pubkey (register on GitHub):"
      echo "  $pubkey"
      echo "==============="
      echo ""
    } > /etc/issue.tmp
    mv /etc/issue.tmp /etc/issue
    cp /etc/issue /etc/motd
  '';
in
{
  systemd.services.devhost-banner = {
    description = "Refresh /etc/issue + /etc/motd with hostname, IPs, pubkey";
    after = [
      "network-online.target"
      "devhost-user-ssh-key.service"
    ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = writeBanner;
    };
  };

  systemd.timers.devhost-banner = {
    description = "Refresh devhost banner every minute";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "10s";
      OnUnitActiveSec = "60s";
      Unit = "devhost-banner.service";
    };
  };
}
